/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameResult {
  'winnerPlayer' : Player,
  'players' : Array<Player>,
  'winnerPlayerIndex' : bigint,
  'turnsPlayed' : bigint,
}
export interface Player { 'hero' : string, 'name' : string }
export interface Room {
  'status' : RoomStatus,
  'code' : string,
  'createdAt' : bigint,
  'level' : bigint,
  'players' : Array<RoomPlayer>,
  'hostId' : string,
  'maxPlayers' : bigint,
}
export interface RoomPlayer {
  'id' : string,
  'name' : string,
  'joinedAt' : bigint,
  'isHost' : boolean,
}
export type RoomStatus = { 'starting' : null } |
  { 'waiting' : null } |
  { 'ready' : null };
export interface _SERVICE {
  'createRoom' : ActorMethod<[string, string, string, bigint, bigint], Room>,
  'getMostPopularHero' : ActorMethod<[], [] | [[string, bigint]]>,
  'getRoomState' : ActorMethod<[string], [] | [Room]>,
  'getTop10ByTurns' : ActorMethod<[], Array<GameResult>>,
  'getTotalGames' : ActorMethod<[], bigint>,
  'joinRoom' : ActorMethod<[string, string, string], [] | [Room]>,
  'leaveRoom' : ActorMethod<[string, string], boolean>,
  'saveGame' : ActorMethod<[GameResult], undefined>,
  'startRoom' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];