/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Player = IDL.Record({ 'hero' : IDL.Text, 'name' : IDL.Text });
export const GameResult = IDL.Record({
  'winnerPlayer' : Player,
  'players' : IDL.Vec(Player),
  'winnerPlayerIndex' : IDL.Nat,
  'turnsPlayed' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getMostPopularHero' : IDL.Func(
      [],
      [IDL.Opt(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getTop10ByTurns' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
  'getTotalGames' : IDL.Func([], [IDL.Nat], ['query']),
  'saveGame' : IDL.Func([GameResult], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Player = IDL.Record({ 'hero' : IDL.Text, 'name' : IDL.Text });
  const GameResult = IDL.Record({
    'winnerPlayer' : Player,
    'players' : IDL.Vec(Player),
    'winnerPlayerIndex' : IDL.Nat,
    'turnsPlayed' : IDL.Nat,
  });
  
  return IDL.Service({
    'getMostPopularHero' : IDL.Func(
        [],
        [IDL.Opt(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getTop10ByTurns' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
    'getTotalGames' : IDL.Func([], [IDL.Nat], ['query']),
    'saveGame' : IDL.Func([GameResult], [], []),
  });
};

export const init = ({ IDL }) => { return []; };