/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    hero: string;
    name: string;
}
export interface Room {
    status: RoomStatus;
    code: string;
    createdAt: bigint;
    level: bigint;
    players: Array<RoomPlayer>;
    hostId: string;
    maxPlayers: bigint;
}
export interface GameResult {
    winnerPlayer: Player;
    players: Array<Player>;
    winnerPlayerIndex: bigint;
    turnsPlayed: bigint;
}
export interface RoomPlayer {
    id: string;
    name: string;
    joinedAt: bigint;
    isHost: boolean;
}
export enum RoomStatus {
    starting = "starting",
    waiting = "waiting",
    ready = "ready"
}
export interface backendInterface {
    createRoom(code: string, hostId: string, hostName: string, maxPlayers: bigint, level: bigint): Promise<Room>;
    getMostPopularHero(): Promise<[string, bigint] | null>;
    getRoomState(code: string): Promise<Room | null>;
    getTop10ByTurns(): Promise<Array<GameResult>>;
    getTotalGames(): Promise<bigint>;
    joinRoom(code: string, playerId: string, playerName: string): Promise<Room | null>;
    leaveRoom(code: string, playerId: string): Promise<boolean>;
    saveGame(gameResult: GameResult): Promise<void>;
    startRoom(code: string, hostId: string): Promise<boolean>;
}
import type { Room as _Room, RoomPlayer as _RoomPlayer, RoomStatus as _RoomStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createRoom(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<Room> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Room_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Room_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMostPopularHero(): Promise<[string, bigint] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMostPopularHero();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMostPopularHero();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomState(arg0: string): Promise<Room | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomState(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomState(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTop10ByTurns(): Promise<Array<GameResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTop10ByTurns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTop10ByTurns();
            return result;
        }
    }
    async getTotalGames(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalGames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalGames();
            return result;
        }
    }
    async joinRoom(arg0: string, arg1: string, arg2: string): Promise<Room | null> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRoom(arg0, arg1, arg2);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRoom(arg0, arg1, arg2);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async leaveRoom(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveRoom(arg0, arg1);
            return result;
        }
    }
    async saveGame(arg0: GameResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGame(arg0);
            return result;
        }
    }
    async startRoom(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.startRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startRoom(arg0, arg1);
            return result;
        }
    }
}
function from_candid_RoomStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomStatus): RoomStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Room_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Room): Room {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[string, bigint]]): [string, bigint] | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Room]): Room | null {
    return value.length === 0 ? null : from_candid_Room_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RoomStatus;
    code: string;
    createdAt: bigint;
    level: bigint;
    players: Array<_RoomPlayer>;
    hostId: string;
    maxPlayers: bigint;
}): {
    status: RoomStatus;
    code: string;
    createdAt: bigint;
    level: bigint;
    players: Array<RoomPlayer>;
    hostId: string;
    maxPlayers: bigint;
} {
    return {
        status: from_candid_RoomStatus_n3(_uploadFile, _downloadFile, value.status),
        code: value.code,
        createdAt: value.createdAt,
        level: value.level,
        players: value.players,
        hostId: value.hostId,
        maxPlayers: value.maxPlayers
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    starting: null;
} | {
    waiting: null;
} | {
    ready: null;
}): RoomStatus {
    return "starting" in value ? RoomStatus.starting : "waiting" in value ? RoomStatus.waiting : "ready" in value ? RoomStatus.ready : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
